task: 'run_zju_mocap'
experiment: 'gneuvox'
now_subject: '387'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.dataset.train'
  dataset: '387_train'

progress:
  dataset_module: 'core.data.dataset.train'
  dataset: '387_test'

movement:
  dataset_module: 'core.data.dataset.train'
  dataset: '387_test'

freeview:
  dataset_module: 'core.data.dataset.freeview'
  dataset: '387_test'
tpose:
  dataset_module: 'core.data.dataset.tpose'
  dataset: '387_test'
eval_cam:
  dataset_module: 'core.data.dataset.eval_cam'
  dataset: '387_test'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
load_net: latest_finish