task: 'do_it'
experiment: 'selfdata'
now_subject: 'selfdata'

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.dataset.train'
  dataset: 'selfdata_train'

progress:
  dataset_module: 'core.data.dataset.train'
  dataset: 'selfdata_test'

movement:
  dataset_module: 'core.data.dataset.train'
  dataset: 'selfdata_test'

freeview:
  dataset_module: 'core.data.dataset.freeview'
  dataset: 'selfdata_test'

tpose:
  dataset_module: 'core.data.dataset.tpose'
  dataset: 'selfdata_test'

eval_cam:
  dataset_module: 'core.data.dataset.eval_cam'
  dataset: 'selfdata_test'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.474
load_net: latest